### ISSUE TITLE
API Design

### ISSUE THREAD

**Issue by andrewgu** [andrewgu/ModConfigMenu#1]
The API design can't be changed once it's out (without a major, non-backwards-compatible revision), so we need to test/refine it several times before we officially release.

**Comment by Superd22** [comment]
Ok, i'm done with midterms which mean i can (finally) give the long awaited feedback. I've tried implementing the framework with one of my own mod just to get a hang of it and see what a set of fresh eyes would uncover.

So, i created a new class "MODName_Optionscreen" to handle everything related to the options.
I have 8 variables 
`var bool DISPLAY_PERK;
var bool DISPLAY_PERK_BACKGROUND;
var int PERK_LINE_SIZE;
var int PERK_NUMBER_PER_LINE;

var bool DISPLAY_STATS;
var bool STATS_VERTICAL;
var bool STATS_HORIZONTAL_ABOVE;	   
var bool STATS_COLORS;`

## > First issue, my config file is bound to another class.
This means first

**Comment by Superd22** [comment]
Ok, i'm done with midterms which mean i can (finally) give the long awaited feedback. I've tried implementing the framework with one of my own mod just to get a hang of it and see what a set of fresh eyes would uncover.

### > Multi-class mod.

I don't think you took into account that fact when designing the API, most mods are multi-class, or will want to set-up their option in a new class for comfort.
**That means the variables holding the settings are in another class.** That means, for every variable :
- Declare a var in the new class.
- Get the base vars from the modclass 
  (Incidentally, this could lead to trouble as config vars are not default and requires an instance of the class running to be accessed. -Which means Spawn(class'MODCLASS') for Actors and new class'MODCLASS' for objects- Potential? performance issues. (Do we intend for the end-user to really garbage collect properly after calling it?)
- On to declaring those setups to MCM_API_Setting.

### > Declaring to MCM_API_Setting
- Is it really necessary to ask the users to init TWO separates array ?
  I guarantee having to populate a name array and then pushing actual UI to the MakeSetting will confuse the hell out of people.
- Having custom callback on individual updated settings is nice for an advanced user, but i think we should offer a shorthand for the small time coder who _just_ wanna add a couple settings.

Example :
In my custom mod i have 6 checkboxes. The same callback is used for each-one : 

```
// Declaration of the settings
    Page1Settings.AddItem('DISPLAY_PERK');  
    Page1Settings.AddItem('DISPLAY_PERK_BACKGROUND');   
[...]
// Which supposes i declared DISPLAY_PERK and co and fetched their current/default value. (see 1/)
    P1S = Page1.MakeSettings(Page1Settings);                                                                                 
    P1S[0].InitAsCheckbox("Display Perk", DISPLAY_PERK, CheckboxChangeHandler);     
    P1S[1].InitAsCheckbox("Display Perk Background", DISPLAY_PERK_BACKGROUND, CheckboxChangeHandler);    
[...]




// Callback function
simulated function CheckboxChangeHandler(MCM_API_Setting Setting) {
    local bool value;
    value = Setting.GetCheckboxValue();

    switch(Setting.GetName()) {
        case 'DISPLAY_PERK': DISPLAY_PERK = value; break;     
        case 'DISPLAY_PERK_BACKGROUND': DISPLAY_PERK_BACKGROUND = value; break;
        case 'DISPLAY_STATS': DISPLAY_STATS = value; break;
        case 'STATS_VERTICAL': STATS_VERTICAL = value; break;
        case 'STATS_HORIZONTAL_ABOVE': STATS_HORIZONTAL_ABOVE = value; break;
        case 'STATS_COLORS': STATS_COLORS = value; break;
    }

}
```

Most people will do just that on every changehandler they create, thinking about the little newbie i think a DefaultBoolChangeHandler(name SettingName, bool Value) would be greatly appreciated. As an added benefit that prevents the user from having to know _anything_ about the structure of a MCM_API_Setting to go ahead. (Which we should encourage.)
- Save/Revert/Reset would need a helper of the same type.
  (Btw, the main save button does not trigger any delegate so you have to EnableSaveAndCancelButtons to save a config.

**Comment by andrewgu** [comment]
Yup, the main save button and tab switching need to trigger handlers. They haven't yet because that's an incomplete part of the UI. :-/

The reason for asking for a list up front is actually a UI limitation when using dropdowns with UIMechaListItem. In order for dropdowns to work without UI bugs, you have to initialize the settings from bottom to top, not top to bottom. If we abandon dropdowns or introduce some sort of "I'm done adding settings" function call, then we can get around the list issue.

I like the idea of default handlers. 

Words are ambiguous, so let's do it this way: why don't you make a pull request where you've edited the MCM_API_**\* files with your suggestions for how the API should work? That way I can look at the exact changes you have in mind, and we can discuss there? I like the ideas, so let's get to the details. :)

**Comment by Superd22** [comment]
Yeah, i know about the bottom to top issue. I really think the i'm done with settings function call is better though.
1/ It's one line versus N lines for the users
2/ We're gonna need one anyway for #6 

It's around midnight here, I'll make the pull tomorrow if you don't mind ;p

**Comment by andrewgu** [comment]
Not at all. Looking forward to seeing your suggestions!

**Comment by andrewgu** [comment]
Closing because remaining API design issues will be small tweaks, and can be discussed in their own issues.
