### ISSUE TITLE
3D Movie Scrolling Doesn't Work When Hovering Over Group Labels

### ISSUE THREAD

**Issue by Patrick-Seymour** [andrewgu/ModConfigMenu#16]
If a Page has a bunch of settings, scrolling doesn't work with the mouse wheel if your mouse cursor is over a Group label. Scrolling does work if your mouse is over a Setting or the scrollbar itself. (Note that this issue only seems to present itself when the mod options are displayed as a 3D screen, scrolling seems to work fine as a 2D screen.)

> andrewgu
> I think we'll leave that as a bug to fix in version 1.1. It's not great, but it also doesn't require API changes, and mostly works.

**Comment by andrewgu** [comment]
Should be fixed now. Will go out with next release.
