### ISSUE TITLE
Save and Exit, Cancel Buttons Unnecessarily Highlighted When UIScreen Loads

### ISSUE THREAD

**Issue by Patrick-Seymour** [andrewgu/ModConfigMenu#17]
The Save and Exit and Cancel buttons are selected by default when the UIScreen loads (see image). I've noticed similar issues with the Guerilla Tactics School list of Upgrade Projects: Labels appear highlighted when the menu loads, but once you mouse over-and-out of each label they appear correctly.

> andrewgu
> yeah, not sure why it's happening, but again I think we can leave it as a 1.1 bug since it's small and should not require API changes, and it's not unique to this particular interface.

**Comment by andrewgu** [comment]
Fixed for now: doesn't look really wrong. Only the Save and Exit button is now highlighted by default.
