### ISSUE TITLE
Tooltips Don't Work

### ISSUE THREAD

**Issue by Patrick-Seymour** [andrewgu/ModConfigMenu#18]
Tooltips don't seem to be working. I don't see tooltips on the vanilla options, even though some of them have tooltips defined using the same method you're using (BG.SetTooltipText). Maybe the vanilla tooltips are just garbage? They do work in some situations, like when you are in UIArmory_Promotion and the right-side ability summary screen shows ability tooltips when you mouse over them (defined in UIUtilities_Strategy.AddAbilitySummaryTooltip or thereabouts).

> andrewgu
> yup, they're broken. I spent some time trying to figure out how it worked in the UIOptionsPCScreen, and I think there's some hard-coding going on in the Scaleform UI. There's a tooltip system in the UI scripts that should be usable, but it may take some time to hook that feature up. I'm inclined to leave the relevant parts in the API and make it a 1.1 feature.

**Comment by andrewgu** [comment]
Leaving a comment here for later investigation. It looks like tooltips are somewhat hardcoded in the Flash layer. However, there are some UITooltip related classes that we might be able to use.

**Comment by andrewgu** [comment]
Moving this to 1.1 release milestone. After staring at the tooltip code for 2 hours, it still feels like a kludgy mess, but the API is abundantly clear on exactly how you're supposed to use tooltips, so I'm going to go ahead with 1.0 with the explicit note of "actually working tooltips are planned for next patch."

**Comment by andrewgu** [comment]
YEEEEEESSSSSSSSSSSSSS! I figured it out. `UIPanel.SetTextTooltip` only works when the panel itself is visible. By adding an "when the panel is made visible" event and hooking that to an extra call to refresh the text tooltips, it now works! Will bundle this into the next release update.
