### ISSUE TITLE
The mod won't hook into LW_Toolbox's override of the options menu

### ISSUE THREAD

**Issue by RealityMachina** [andrewgu/ModConfigMenu#26]
This should be fairly easy to fix on your end, but before too many mod authors try implementing MCM support and get flooded with complaints about it: as is MCM is completely incompatible with the Toolbox because of how it's structured.

Specifically the problem is this in MCM_OptionsMenuListener:
`defaultproperties
{
    ScreenClass = class'UIOptionsPCScreen';
}`

That part of the code will not hook into any classes that override what's specified there, it will look for only UIOptionsPCScreen, and will not hook into the Toolbox's UIOptionsPCScreen_LW.

What you want to do instead is set that to none and instead do the filtering like this:

```
event OnInit(UIScreen Screen)
{
    `log("MCM Listener OnInit");

 if(UIOptionsPCScreen(Screen) != none)
 {
     if (ENABLE_MENU)
     {
         InjectModOptionsButton();
     }
 }
}
```

When filtered in there, it will catch any classes that happen to be overriding the UI class it's looking for, fixing both problems with the toolbox and any future mods that end up overriding the class as well.

EDIT:

[It occurred to me that I could just make a pull request for this.](https://github.com/andrewgu/ModConfigMenu/pull/27)

**Comment by andrewgu** [comment]
Merged, tested, and uploaded! Thanks for the PR!
