### ISSUE TITLE
defaultproperties not properly assigned?

### ISSUE THREAD

**Issue by robojumper** [andrewgu/ModConfigMenu#32]
MCM_UISettingSeparator.uc, MCM_GroupLabelSeparator.uc

```
defaultproperties {
    TITLE_X = 7;
    TITLE_Y = 8;
    DESC_X  = 7;
    DESC_Y  = 20;
}
```

According to [1](https://forums.nexusmods.com/index.php?/topic/3857305-uitacticalhud-screen-listener-not-respecting-screenclass/page-2), [2](http://udn.epicgames.com/Three/UnrealScriptDefaultProperties.html) the opening brace MUST be on a new line. Otherwise the variables won't have any effect.

**Comment by andrewgu** [comment]
Well... that explains why I was having issues with layout on these widgets. Thanks!

**Comment by andrewgu** [comment]
Closing, fix will roll out with the next release on Steam/Nexus. Will fix a few additional issues before that release.
