### ISSUE TITLE
Minor issue with links on nexus page

### ISSUE THREAD

**Issue by skwerlman** [andrewgu/ModConfigMenu#40]
The links in the description on the nexus are outgoing steamcommunity links, so when you click then, you get a big warning about leaving steam (even though you aren't)

For example:
on the nexus
`https://github.com/andrewgu/ModConfigMenu`
has the url
`https://steamcommunity.com/linkfilter/?url=https://github.com/andrewgu/ModConfigMenu`

Also, `http://steamcommunity.com/sharedfiles/filedetails/?id=667104300` is shown as plain text.

**Comment by andrewgu** [comment]
Oops. Thanks for reporting, will fix.
