### ISSUE TITLE
Init and SetBounds don't set increment/decrement step size on MCM_Slider

### ISSUE THREAD

**Issue by andrewgu** [andrewgu/ModConfigMenu#47]
This bug shows up because after PR-45 MCM_Slider no longer calls SetStepSize to configure the increment/decrement size for actual slider control.

**Comment by BlueRaja** [comment]
You're mixing tabs and spaces 😛

**Comment by andrewgu** [comment]
Ugh, Visual Studio configurations.

**Comment by andrewgu** [comment]
Fixed tabs and spaces issue in #49
