### ISSUE TITLE
InitAs : Tooltips & Description

### ISSUE THREAD

**Issue by Superd22** [andrewgu/ModConfigMenu#5]
For every MCM_API_Setting you should be able to declare a Tooltip (on-hover help text to indicate what a setting does.)
- Related, InitAsLabel might be improved with a "Description" paramaters, would a mod user wish to create "sections of settings" separated with a label and a small description.

ie : 
### General Setting

Tweak everything general
- Setting 1
- Setting 2
### Advanced setting

You should really think about changing those as they are advanced.
- Setting 3
- Setting 4

**Comment by andrewgu** [comment]
Agreed on the tooltips. 

Let's talk about categories though. Do you think we should introduce a "category" concept in the API, or just keep the "InitAsLabel" concept? When I wrote in "InitAsLabel" I had short lines of text in mind, not category headers. If we want categories, I think it's worth abstracting _how_ the categories are shown.

**Comment by Superd22** [comment]
I think the InitAsLabel is redondant. Either you're trying to describe a single setting and tooltip is the way to go, or you're trying to describe a bunch of settings and then you're categorizing them.

In any case, we should definitely abstract it.

**Comment by andrewgu** [comment]
"Tooltips don't work" is now a separate issue, so I'm closing this one since InitAs has been replaced with "Add***" and proper grouping has been implemented, and the API allows for tooltips even though getting the actual tooltip to render seems to be inconsistent.
