### ISSUE TITLE
Lazy loading implementation breaks SaveStateHandlers which try to get settings from the page passed as parameter

### ISSUE THREAD

**Issue by qacha** [andrewgu/ModConfigMenu#54]
A mod that needs to access individual settings in one of the page-level handlers (say, to implement ResetHandler) but doesn't keep references to these settings as instance variables (to avoid the garbage collection-related issues mentioned in the tutorial) could, until recently, find the relevant setting objects from the SettingsPage parameter by using GetGroupByName and GetSettingByName.

The recent introduction of MCM_SettingsPanelFacade broke this functionality. The SettingsPage parameter passed to these handlers is the MCM_SettingsPanel (not the MCM_SettingsPanelFacade), meaning GetGroupByName will always return none.

At a glance, it seems like MCM_SettingsPanel could hold a reference to the MCM_SettingsPanelFacade (populated in MCM_SettingsPanelFacade.CreateUi) that it could pass to all three SaveStateHandlers instead of self to fix this.

**Comment by andrewgu** [comment]
Thanks for the bug report. I will investigate.

In theory MCM_SettingsPanelFacade should be transparent because the API level guarantees are for the MCM_API_### interface, but it looks like I missed a spot because of the splitting of where Groups are actually tracked now.

**Comment by qacha** [comment]
The problem is that MCM_SettingsPanel.OnResetClicked (and its friends too, I think, but it's the only one I tried) passes the MCM_SettingsPanel to the ResetHandler instead of the MCM_SettingsPanelFacade. And while MCM_SettingsPanel implements MCM_API_SettingsPage, its implementation for anything dealing with groups (AddGroup, GetGroupByName, GetGroupByIndex, GetGroupCount) don't do anything, including returning a useful value.

**Comment by andrewgu** [comment]
Should be fixed in PR #55, I will publish to Steam and Nexus shortly.
